version: 2.1
jobs:
  compile:
   docker:
      - image: xyzuan/xdocker:latest
   steps:
      - run:
          command: |
            git clone --depth=1 https://github.com/Plankton86/android_kernel_asus_sdm660.git -b RTX-NLV-S kernel && cd kernel
            curl https://raw.githubusercontent.com/Plankton86/My_Kernel_Builder_BPF/main/build.sh > run.sh
            source run.sh
          no_output_timeout : 5h
workflows:
  version: 2.1
  cooking:
    jobs:
      - compile 
      
